services:
  webserver_staff_api:
    container_name: terravie_nginx_staff_api
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        PHP_FPM_SERVER: terravie_php_staff_api
        PHP_FPM_PORT: 9000
    ports:
      - '${DOCKER_NGINX_PORT-8001}:80'
    networks:
      - backend
    depends_on:
      - app_staff_api

  app_staff_api:
    container_name: terravie_php_staff_api
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        XDEBUG: 'true'
    volumes:
      - '.:/var/www/html'
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - backend

networks:
  backend:
    name: terravie_network
    driver: bridge
    external: true
